### ISSUE TITLE
Can't build with npm

### ISSUE THREAD

**Issue by jasonwmatteson** [hawkeye64/electron-quasar-file-explorer-v2#6]
First off awesome that you put this out!  Need to build something similar on my end.

However, I can't run it on my Mac Pro 16". When i try to `npm install`, I get a TON of errors. If I force it (`npm install --force`), it will run in dev mode (`quasar dev -m electron`) but then I get:

Error occurred in handler for 'myShell:getMimeType': TypeError: mime__WEBPACK_IMPORTED_MODULE_4___default(...).lookup is not a function
    at eval (webpack://electron-quasar-file-explorer-v2/./src-electron/handler.js?:86:56)
    at node:electron/js2c/browser_init:189:579
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11093)
    at EventEmitter.emit (node:events:390:28)

Ideas?

**Comment by jasonwmatteson** [comment]
To add to this, I'm using node v16.18.0 & npm v8.19.2.

**Comment by hawkeye64** [comment]
Please use `Yarn` and not `npm`
